### Login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "john",
    "password": "john"
}

### List products

GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTcwNzEyODI1NCwiZXhwIjoxNzA3MjE0NjU0fQ.NkMx7Xh0Uj9i18XAIB2cfexau7Tt_JQmfSO6z2LxQ30


###

POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTcwNzEyODI1NCwiZXhwIjoxNzA3MjE0NjU0fQ.NkMx7Xh0Uj9i18XAIB2cfexau7Tt_JQmfSO6z2LxQ30

{
    "id": "c488eb5c-9db6-47d0-ae46-f1daa8pr1004",
    "name": "Relogio 04",
    "description": "Relogio 04 description",
    "image_url": "https://cdn.ttgtmedia.com/rms/onlineimages/hp_elitebook.jpg",
    "price": 101
}

###
GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTcwNzEyODI1NCwiZXhwIjoxNzA3MjE0NjU0fQ.NkMx7Xh0Uj9i18XAIB2cfexau7Tt_JQmfSO6z2LxQ30

### Get One
GET http://localhost:3000/orders/8a80c98f-6cac-4c61-914d-9af98c02793d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTcwNzEyODI1NCwiZXhwIjoxNzA3MjE0NjU0fQ.NkMx7Xh0Uj9i18XAIB2cfexau7Tt_JQmfSO6z2LxQ30


###

POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTcwNzEyODI1NCwiZXhwIjoxNzA3MjE0NjU0fQ.NkMx7Xh0Uj9i18XAIB2cfexau7Tt_JQmfSO6z2LxQ30

{
    "items": [
        {
            "product_id": "1cb53ac4-3b35-4cac-a68f-eb145c380001",
            "quantity": 2
        },
        {
            "product_id": "1cb53ac4-3b35-4cac-a68f-eb145c380003",
            "quantity": 6
        }
    ],
    "card_hash": "1and3"
}

